### ISSUE TITLE
Review "Alternativlos"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#10]
Link: https://alternativlos.org/

**Comment by andygrunwald** [comment]
Great Podcast, but I am not sure if this should be part of this german tech podcast list. Why? Because the focus is mostly on politics, fun with a theme of digitalization, rather than on tech:

> Warum Alternativlos? Da haben wir uns [an Politikern orientiert](http://neusprech.org/alternativlos/), die ihre Vorhaben gerne damit begründen, dass sie angeblich „ohne Alternative“ oder „alternativlos“ sind. Begründungen von Gesetzen enthalten praktisch immer den Absatz „Alternativen: keine“. Wir sehen das ähnlich: Für uns gab es keine Alternative dazu, endlich einen Boulevard-Podcast zu machen. Der Fokus liegt auf Spaß und thematischer Breite, nicht so sehr auf Fakten, journalistischer Sorgfalt oder ähnlichen Unterhaltungsbremsen. Nachlesen und herausfinden, was wirklich passiert ist, sollt ihr schließlich selbst :-)

I believe those are important topics but might not match the theme here.

@woolfg What is your opinion?

**Comment by woolfg** [comment]
I think it would be relevant if it was still active. last episode [5.12.2021](https://alternativlos.org/49/) so I would not add it. If it becomes active again we will add it.
