### ISSUE TITLE
What is podcastIndexID ?

### ISSUE THREAD

**Issue by ewolff** [EngineeringKiosk/GermanTechPodcasts#118]
I was considering to submit another podcast, but I am not sure what podcastIndexID is and how to get it for a podcast. Can you point me to some documentation? Thanks!

**Comment by woolfg** [comment]
you can find the id at https://podcastindex.org/ - e.g. https://podcastindex.org/podcast/4957030

**Comment by ewolff** [comment]
Great, thanks. Actually, I just noticed this was an RTFM. Sorry.
