### ISSUE TITLE
Review "CRE"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#13]
Link: https://cre.fm/

**Comment by andygrunwald** [comment]
CRE is not a pure Tech podcast, but one about Technology, Society and Culture.
This leads to a mix of topics like
- Digital money
- Terravision
- [Die Sendung mit der Maus](https://cre.fm/cre223-die-sendung-mit-der-maus)
- Bats
- ...

A very wide range. Mainly interviews.
I would suggest to not add this.

**Comment by woolfg** [comment]
less then 70% tech and more on culture and society, borderline but wouldn't at it so the moment
