### ISSUE TITLE
Bundling via OPML ?

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#157]
render german tech podcasts as OPML as suggested by sebastian@netzpolitik

See https://www.podcast.de/faq/antwort-60-was-ist-opml

**Comment by woolfg** [comment]
should be a big deal to render our list in OPML, like it :+1:

**Comment by andygrunwald** [comment]
On our website, https://engineeringkiosk.dev/deutsche-tech-podcasts/, we have the OPML file now available: https://engineeringkiosk.dev/deutsche-tech-podcasts/podcasts.opml

Import was tested via Pocket Casts on iOS App.

**Comment by andygrunwald** [comment]
See https://github.com/EngineeringKiosk/webpage/issues/316
