### ISSUE TITLE
Review "Click! Clack! Hack!"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#19]
Link: https://www.nerdbude.com/podcast/

**Comment by andygrunwald** [comment]
This is a podcast only about mechanical keyboards.
In my opinion this is not a good fit for this tech podcast list.

Before closing this issue, awaiting feedback from @woolfg about this.

**Comment by woolfg** [comment]
very niche but it is hardware...

**Comment by andygrunwald** [comment]
After we have created a definition on what "tech" means, this podcast fits totally in: https://github.com/EngineeringKiosk/GermanTechPodcasts/blob/main/CONTRIBUTING.md#what-is-tech-in-this-context
