### ISSUE TITLE
Review "ISMS X-Plain"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#214]
See https://www.abat.de/expertenwissen/podcast-isms-x-plain

**Comment by andygrunwald** [comment]
This Podcast is mainly about Information Security Management System (ISMS):

> Ein Information Security Management System ist die Aufstellung von Verfahren und Regeln innerhalb einer Organisation, die dazu dienen, die Informationssicherheit dauerhaft zu definieren, zu steuern, zu kontrollieren, aufrechtzuerhalten und fortlaufend zu verbessern.

It touches the topic of information security.
But this sounds more like in the Auditing area rather then tech area.

Hence, I am voting to not include this podcast in the list.

**Comment by woolfg** [comment]
ISO/IEC 27001 information security topics are definitely IT topics, would suggest to include it.
