### ISSUE TITLE
Review "Mein Scrum ist kaputt!"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#32]
Link: https://meinscrumistkaputt.de/

**Comment by woolfg** [comment]
scrum only, but could be very relevant for devs and team culture? is it in scope @andygrunwald ?

**Comment by andygrunwald** [comment]
IMO yes, because this is part of the modern tech and it world.
One (if not THE) method to plan projects.

@woolfg Feel free to make a PR.
