### ISSUE TITLE
Review "Heise Podcasts"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#46]
Link: https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html

Which one? All? A few?

**Comment by andygrunwald** [comment]
* [Kurz informiert by heise online](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_3) – der News-Podcast (werktäglich)
* [Zahlen, bitte!](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#zahlenbitte) – spannende, skurrile und wichtige Zahlen (dienstags)
* [#heiseshow](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_1) – die wöchentliche Dosis Technik und Netzpolitik (donnerstags)
* [c't uplink](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_2) – der Podcast aus Nerdistan (samstags)
* [Bit-Rauschen](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_bitrauschen) – der Prozessor-Podcast von c't (14-täglich)
* [Auslegungssache](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anker_auslegungssache) – der c't-Datenschutz-Podcast (14-täglich)
* [c't-SciFiCast](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#ctstories) – Pechschwarze Technikmomente (14-täglich)
* [Mac & i](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_macandi) – der Apple-Podcast (monatlich)
* [SoftwareArchitekTOUR](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_4) – von Entwicklern für Entwickler (monatlich)
* [Tech2go](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#tech2go) – Technology Review debattiert über Innovationen (monatlich)
* [Die Hupe](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anchor_hupe) – der laut-starke Mobilitäts-Podcast zu Auto, Motorrad und mehr (monatlich)
* [heise meets ...](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#heisemeets) – der Entscheider-Talk von Entscheidern für Entscheider (14-täglich)

**Comment by andygrunwald** [comment]
@woolfg Please check the [Auslegungssache](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anker_auslegungssache) – der c't-Datenschutz-Podcast (14-täglich) podcast

**Comment by woolfg** [comment]
I would propose to add "[Auslegungssache](https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html#anker_auslegungssache)" and mark it as "society impact" podcast?

**Comment by andygrunwald** [comment]
Auslegungssache added in #75
