### ISSUE TITLE
Review "Umbruch"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#83]
Link: https://www.br.de/mediathek/podcast/umbruch-der-tech-podcast-von-br24/648

**Comment by woolfg** [comment]
for me it is borderline as "Tech topics explained for non-tech people". those podcasts exist by almost all public radio stations. I am also listening to it, e.g. https://oe1.orf.at/collection/582279 but I would not add them for now, as there are many and usually they are for a broader audience.

**Comment by andygrunwald** [comment]
Decision taken.
