### ISSUE TITLE
Review "FAZ Digitec"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#86]
Link: https://open.spotify.com/show/2tKSpYEvw02J8Bl19ZXStB?si=ukbYupN5TmCndDd9n9yhFQ&nd=1

**Comment by andygrunwald** [comment]
Here i am not really sure. The description is:
> Im Digitec-Podcast sprechen die Redakteure der FAZ über neue Entwicklungen in der digitalen Wirtschaft, in der Industrie 4.0 - und in der Technik. Wir diskutieren miteinander und auch mit Gästen – dabei ordnen wir die aktuellen Themen rund um Digitalisierung und Technologie ein. Dabei geht es nicht nur um Bits und Bytes, sondern auch um einen größeren gesellschaftlichen Kontext.

The topics of the episodes are
- Evaluation (business wise) of Bigtech
- Why is TikTok successful
- Tech Stocks
- Intelligent city

My suggestion: Not adding this one.

**Comment by woolfg** [comment]
Abkürzung to our rules we don't add 'Tech topics explained for non-tech people' ... therefore, I would suggest not adding it.

**Comment by andygrunwald** [comment]
Decision done.
